ISSITES-6093 update info/widget templates and add specification template
silasbsi/liferay-portal pull request #45
Opened 2023-06-13 17:14 UTC by jotchon

2023-06-15 23:27 UTC, silasbsi requested changes
Good job, but I added some suggestions.

2023-06-15 23:27 UTC, silasbsi commented on modules/apps/site-initializer/site-initializer-liferay-marketplace/src/main/resources/site-initializer/ddm-templates/marketplace-vocabulary-facets/ddm-template.ftl
> +</style>
Could you please format these styles? Brian always asks us to do this.
```suggestion
<style>
   .vocab-facet {
 	   border-radius: 10px;
   }

   .vocab-facet .panel a {
	   padding: 1rem;
   }

   .vocab-facet .collapse-icon .collapse-icon-closed .lexicon-icon,
   .vocab-facet .collapse-icon .collapse-icon-open .lexicon-icon {
	   margin-top: 0.3rem;
   }

   .vocab-facet .panel-body {
	   padding: 0.5rem 1rem 1rem;
   }

   .vocab-facet .list-unstyled {
	   margin-bottom: 0;
   }
</style>
```

2023-06-15 23:27 UTC, silasbsi commented on modules/apps/site-initializer/site-initializer-liferay-marketplace/src/main/resources/site-initializer/ddm-templates/price-model-specification-facet/ddm-template.ftl
> +<@liferay_ui["panel-container"]
Could you please format these styles? Brian always asks us to do this.
```suggestion
<style>
   .price-model-facet {
	   border-radius: 10px;
   }

   .price-model-facet .panel a {
	   padding: 1rem;
   }

   .price-model-facet .collapse-icon .collapse-icon-closed .lexicon-icon,
   .price-model-facet .collapse-icon .collapse-icon-open .lexicon-icon {
	   margin-top: 0.3rem;
   }

   .price-model-facet .panel-body {
	   padding: 0.5rem 1rem 1rem;
   }

   .price-model-facet .list-unstyled {
	   margin-bottom: 0;
   }
</style>

<@liferay_ui["panel-container"]
```

2023-06-15 23:27 UTC, silasbsi commented on modules/apps/site-initializer/site-initializer-liferay-marketplace/src/main/resources/site-initializer/ddm-templates/solutions-search-results/ddm-template.ftl
>  <style type="text/css">
Could you please format this file?

2023-06-15 23:27 UTC, silasbsi commented on modules/apps/site-initializer/site-initializer-liferay-marketplace/src/main/resources/site-initializer/ddm-templates/solutions-search-results/ddm-template.ftl
>  <style type="text/css">
Could you please format this file?

2023-06-16 23:05 UTC, jotchon commented
Opened a PR at [#4329](https://github.com/pt-liferay-solutions/liferay-portal/pull/4329)

2023-06-16 23:05 UTC, closed without merging